-- 총 25개 테이블
select * from tblQnaCategory;
select * from tblQnaComment;
select * from tblQnaBoard;
select * from tblFreeBoard;
select * from tblFreeCommentBoard;
select * from tblMypage;
select * from tblMember;
select * from tblMemberLv;
select * from tblLv;
select * from tblLikeProduct;
select * from tblReview;
select * from tblMemberCart;
select * from tblNotice;
select * from tblProduct;
select * from tblDeliver;
select * from tblAdmin;
select * from tblCategory;
select * from tblNonmemberBasket;
select * from tblTip;
select * from tblIngredient;
select * from tblStore;
select * from tblNonmemberOrder;
select * from tblMemberOrder;
select * from tblSubscribe;
select * from tblNutritionalIngredients;




update tblProduct set productimage = 'product_1.png' where productSeq = 1;
update tblProduct set productimage = 'product_2.png' where productSeq = 2;
update tblProduct set productimage = 'product_3.png' where productSeq = 3;
update tblProduct set productimage = 'product_4.png' where productSeq = 4;
update tblProduct set productimage = 'product_5.png' where productSeq = 5;
update tblProduct set productimage = 'product_6.png' where productSeq = 6;
update tblProduct set productimage = 'product_7.png' where productSeq = 7;
update tblProduct set productimage = 'product_8.png' where productSeq = 8;
update tblProduct set productimage = 'product_9.png' where productSeq = 9;
update tblProduct set productimage = 'product_10.png' where productSeq = 10;
update tblProduct set productimage = 'product_11.png' where productSeq = 11;
update tblProduct set productimage = 'product_12.png' where productSeq = 12;
update tblProduct set productimage = 'product_13.png' where productSeq = 13;
update tblProduct set productimage = 'product_14.png' where productSeq = 14;
update tblProduct set productimage = 'product_15.png' where productSeq = 15;
update tblProduct set productimage = 'product_16.png' where productSeq = 16;
update tblProduct set productimage = 'product_17.png' where productSeq = 17;
update tblProduct set productimage = 'product_18.png' where productSeq = 18;
update tblProduct set productimage = 'product_19.png' where productSeq = 19;
update tblProduct set productimage = 'product_20.png' where productSeq = 20;
update tblProduct set productimage = 'product_21.png' where productSeq = 21;
update tblProduct set productimage = 'product_22.png' where productSeq = 22;
update tblProduct set productimage = 'product_23.png' where productSeq = 23;
update tblProduct set productimage = 'product_24.png' where productSeq = 24;
update tblProduct set productimage = 'product_25.png' where productSeq = 25;
update tblProduct set productimage = 'product_26.png' where productSeq = 26;
update tblProduct set productimage = 'product_27.png' where productSeq = 27;
update tblProduct set productimage = 'product_28.png' where productSeq = 28;
update tblProduct set productimage = 'product_29.png' where productSeq = 29;
update tblProduct set productimage = 'product_30.png' where productSeq = 30;
update tblProduct set productimage = 'product_31.png' where productSeq = 31;
update tblProduct set productimage = 'product_32.png' where productSeq = 32;
update tblProduct set productimage = 'product_33.png' where productSeq = 33;
update tblProduct set productimage = 'product_34.png' where productSeq = 34;
update tblProduct set productimage = 'product_35.png' where productSeq = 35;
update tblProduct set productimage = 'product_36.png' where productSeq = 36;
update tblProduct set productimage = 'product_37.png' where productSeq = 37;
update tblProduct set productimage = 'product_38.png' where productSeq = 38;
update tblProduct set productimage = 'product_39.png' where productSeq = 39;
update tblProduct set productimage = 'product_40.png' where productSeq = 40;
update tblProduct set productimage = 'product_41.png' where productSeq = 41;
update tblProduct set productimage = 'product_42.png' where productSeq = 42;
update tblProduct set productimage = 'product_43.png' where productSeq = 43;
update tblProduct set productimage = 'product_44.png' where productSeq = 44;
update tblProduct set productimage = 'product_45.png' where productSeq = 45;
update tblProduct set productimage = 'product_46.png' where productSeq = 46;
update tblProduct set productimage = 'product_47.png' where productSeq = 47;
update tblProduct set productimage = 'product_48.png' where productSeq = 48;
update tblProduct set productimage = 'product_49.png' where productSeq = 49;
update tblProduct set productimage = 'product_50.png' where productSeq = 50;
update tblProduct set productimage = 'product_51.png' where productSeq = 51;
update tblProduct set productimage = 'product_52.png' where productSeq = 52;
update tblProduct set productimage = 'product_53.png' where productSeq = 53;
update tblProduct set productimage = 'product_54.png' where productSeq = 54;
update tblProduct set productimage = 'product_55.png' where productSeq = 55;
update tblProduct set productimage = 'product_56.png' where productSeq = 56;
update tblProduct set productimage = 'product_57.png' where productSeq = 57;
update tblProduct set productimage = 'product_58.png' where productSeq = 58;
update tblProduct set productimage = 'product_59.png' where productSeq = 59;
update tblProduct set productimage = 'product_60.png' where productSeq = 60;
update tblProduct set productimage = 'product_61.png' where productSeq = 61;
update tblProduct set productimage = 'product_62.png' where productSeq = 62;
update tblProduct set productimage = 'product_63.png' where productSeq = 63;
update tblProduct set productimage = 'product_64.png' where productSeq = 64;
update tblProduct set productimage = 'product_65.png' where productSeq = 65;
update tblProduct set productimage = 'product_66.png' where productSeq = 66;
update tblProduct set productimage = 'product_67.png' where productSeq = 67;
update tblProduct set productimage = 'product_68.png' where productSeq = 68;
update tblProduct set productimage = 'product_69.png' where productSeq = 69;
update tblProduct set productimage = 'product_70.png' where productSeq = 70;
update tblProduct set productimage = 'product_71.png' where productSeq = 71;
update tblProduct set productimage = 'product_72.png' where productSeq = 72;
update tblProduct set productimage = 'product_73.png' where productSeq = 73;
update tblProduct set productimage = 'product_74.png' where productSeq = 74;
update tblProduct set productimage = 'product_75.png' where productSeq = 75;
update tblProduct set productimage = 'product_76.png' where productSeq = 76;
update tblProduct set productimage = 'product_77.png' where productSeq = 77;
update tblProduct set productimage = 'product_78.png' where productSeq = 78;
update tblProduct set productimage = 'product_79.png' where productSeq = 79;
update tblProduct set productimage = 'product_80.png' where productSeq = 80;
update tblProduct set productimage = 'product_81.png' where productSeq = 81;
update tblProduct set productimage = 'product_82.png' where productSeq = 82;






update tblProduct set productimage = 'product_32.png';
update tblProduct set productimage = 'product_33.png';
update tblProduct set productimage = 'product_34.png';
update tblProduct set productimage = 'product_35.png';
update tblProduct set productimage = 'product_36.png';
update tblProduct set productimage = 'product_37.png';
update tblProduct set productimage = 'product_38.png';
update tblProduct set productimage = 'product_39.png';
update tblProduct set productimage = 'product_40.png';
update tblProduct set productimage = 'product_41.png';
update tblProduct set productimage = 'product_42.png';
update tblProduct set productimage = 'product_43.png'; 
update tblProduct set productimage = 'product_44.png';
update tblProduct set productimage = 'product_45.png';
update tblProduct set productimage = 'product_46.png';
update tblProduct set productimage = 'product_47.png';
update tblProduct set productimage = 'product_48.png';
update tblProduct set productimage = 'product_49.png' where productSeq = 49;
update tblProduct set productimage = 'product_50.png' where productSeq = 50;
update tblProduct set productimage = 'product_51.png' where productSeq = 51;
update tblProduct set productimage = 'product_52.png' where productSeq = 52;
update tblProduct set productimage = 'product_53.png' where productSeq = 53;
update tblProduct set productimage = 'product_54.png' where productSeq = 54;
update tblProduct set productimage = 'product_55.png' where productSeq = 55;
update tblProduct set productimage = 'product_56.png' where productSeq = 56;
update tblProduct set productimage = 'product_57.png' where productSeq = 57;
update tblProduct set productimage = 'product_58.png' where productSeq = 58;
update tblProduct set productimage = 'product_59.png' where productSeq = 59;
update tblProduct set productimage = 'product_60.png' where productSeq = 60;
update tblProduct set productimage = 'product_61.png' where productSeq = 61;
update tblProduct set productimage = 'product_62.png' where productSeq = 62;
update tblProduct set productimage = 'product_63.png' where productSeq = 63;
update tblProduct set productimage = 'product_64.png' where productSeq = 64;
update tblProduct set productimage = 'product_65.png' where productSeq = 65;
update tblProduct set productimage = 'product_66.png' where productSeq = 66;
update tblProduct set productimage = 'product_67.png' where productSeq = 67;
update tblProduct set productimage = 'product_68.png' where productSeq = 68;
update tblProduct set productimage = 'product_69.png' where productSeq = 69;
update tblProduct set productimage = 'product_70.png' where productSeq = 70;
update tblProduct set productimage = 'product_71.png' where productSeq = 71;
update tblProduct set productimage = 'product_72.png' where productSeq = 72;
update tblProduct set productimage = 'product_73.png' where productSeq = 73;
update tblProduct set productimage = 'product_74.png' where productSeq = 74;
update tblProduct set productimage = 'product_75.png' where productSeq = 75;
update tblProduct set productimage = 'product_76.png' where productSeq = 76;
update tblProduct set productimage = 'product_77.png' where productSeq = 77;
update tblProduct set productimage = 'product_78.png' where productSeq = 78;
update tblProduct set productimage = 'product_79.png' where productSeq = 79;
update tblProduct set productimage = 'product_80.png' where productSeq = 80;
update tblProduct set productimage = 'product_81.png' where productSeq = 81;
update tblProduct set productimage = 'product_82.png' where productSeq = 82;